#pragma once
#pragma warning(disable : 4996)

#define POOLVULNDRV_DEVICE 0xdead
#define VULN_POOL_TAG 'daed'

// 0xDEAD2003
#define IOCTL_ALLOC_OVERFLOW_BUFFER \
    CTL_CODE(POOLVULNDRV_DEVICE, 0X800, METHOD_NEITHER, FILE_ANY_ACCESS)

// 0xDEAD2007
#define IOCTL_FREE_OVERFLOW_BUFFER \
    CTL_CODE(POOLVULNDRV_DEVICE, 0X801, METHOD_NEITHER, FILE_ANY_ACCESS)

// 0xDEAD200B
#define IOCTL_TRIGGER_OVERFLOW \
    CTL_CODE(POOLVULNDRV_DEVICE, 0X802, METHOD_NEITHER, FILE_ANY_ACCESS)

typedef struct _ALLOCATED_BUFFER_INFO
{
    ULONG_PTR Buffer;
    ULONG Size;
    ULONG PoolTag;
} ALLOCATED_BUFFER_INFO, *PALLOCATED_BUFFER_INFO;